# Generated by Django 5.0.2 on 2024-02-18 14:47

import django.core.validators
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationaldocument',
            old_name='document_file',
            new_name='graduation',
        ),
        migrations.RemoveField(
            model_name='educationaldocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='educationaldocument',
            name='title',
        ),
        migrations.AddField(
            model_name='educationaldocument',
            name='inter',
            field=models.FileField(null=True, upload_to=home.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='educationaldocument',
            name='post_graduation',
            field=models.FileField(blank=True, upload_to=home.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='educationaldocument',
            name='ssc',
            field=models.FileField(null=True, upload_to=home.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
